<?php

return [

    "CREDITCARD_URL" => env("CREDITCARD_URL"),
    "CREDITCARD_KEY" => env("CREDITCARD_KEY"),
    "CREDITCARD_SECRET" => env("CREDITCARD_SECRET"),
    "CREDITCARD_MERCHANTID" => env("CREDITCARD_MERCHANTID"),

    "PAYPAL_URL" => env("PAYPAL_URL"),
    "PAYPAL_CLIENT_ID" => env("PAYPAL_CLIENT_ID"),
    "PAYPAL_CLIENT_SECRET" => env("PAYPAL_CLIENT_SECRET")

];